### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by SylveonBottle** [nullworks/cathook-ipc-web-panel#4]
Thrown randomly after using ./start with catbot-setup.

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Function.listen (/home/USER1/catbot-setup/account-generator/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/USER1/catbot-setup/account-generator/app.js:396:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```

Doesn't seem to crash. May not be important.

**Comment by BenCat07** [comment]
Something was already running on that port, the port is for the account generator and not the web panel though
